/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VsCompetitorRouteImport } from './routes/vs.$competitor'
import { Route as ExamplesSlugRouteImport } from './routes/examples.$slug'
import { Route as DocsSdkRouteImport } from './routes/docs.sdk'
import { Route as DocsSchemaRouteImport } from './routes/docs.schema'
import { Route as CompaniesTickerRouteImport } from './routes/companies.$ticker'
import { Route as ApiPublicV1SearchRouteImport } from './routes/api/public/v1/search'
import { Route as ApiPublicV1QuoteRouteImport } from './routes/api/public/v1/quote'
import { Route as ApiPublicV1InsiderRouteImport } from './routes/api/public/v1/insider'
import { Route as ApiPublicV1FundamentalsRouteImport } from './routes/api/public/v1/fundamentals'
import { Route as ApiPublicV1FilingsRouteImport } from './routes/api/public/v1/filings'
import { Route as ApiPublicV1CompanyRouteImport } from './routes/api/public/v1/company'
import { Route as ApiPublicV1ClustersRouteImport } from './routes/api/public/v1/clusters'
import { Route as ApiPublicV1FilingsBatchRouteImport } from './routes/api/public/v1/filings.batch'
import { Route as ApiPublicV1InternalDispatchWebhooksRouteImport } from './routes/api/public/v1/_internal/dispatch-webhooks'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCompetitorRoute = VsCompetitorRouteImport.update({
  id: '/vs/$competitor',
  path: '/vs/$competitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSlugRoute = ExamplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamplesRoute,
} as any)
const DocsSdkRoute = DocsSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSchemaRoute = DocsSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => DocsRoute,
} as any)
const CompaniesTickerRoute = CompaniesTickerRouteImport.update({
  id: '/companies/$ticker',
  path: '/companies/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SearchRoute = ApiPublicV1SearchRouteImport.update({
  id: '/api/public/v1/search',
  path: '/api/public/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QuoteRoute = ApiPublicV1QuoteRouteImport.update({
  id: '/api/public/v1/quote',
  path: '/api/public/v1/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InsiderRoute = ApiPublicV1InsiderRouteImport.update({
  id: '/api/public/v1/insider',
  path: '/api/public/v1/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FundamentalsRoute = ApiPublicV1FundamentalsRouteImport.update({
  id: '/api/public/v1/fundamentals',
  path: '/api/public/v1/fundamentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FilingsRoute = ApiPublicV1FilingsRouteImport.update({
  id: '/api/public/v1/filings',
  path: '/api/public/v1/filings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CompanyRoute = ApiPublicV1CompanyRouteImport.update({
  id: '/api/public/v1/company',
  path: '/api/public/v1/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClustersRoute = ApiPublicV1ClustersRouteImport.update({
  id: '/api/public/v1/clusters',
  path: '/api/public/v1/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FilingsBatchRoute = ApiPublicV1FilingsBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ApiPublicV1FilingsRoute,
} as any)
const ApiPublicV1InternalDispatchWebhooksRoute =
  ApiPublicV1InternalDispatchWebhooksRouteImport.update({
    id: '/api/public/v1/_internal/dispatch-webhooks',
    path: '/api/public/v1/dispatch-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/companies/$ticker': typeof CompaniesTickerRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs/schema': typeof DocsSchemaRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/api/public/v1/clusters': typeof ApiPublicV1ClustersRoute
  '/api/public/v1/company': typeof ApiPublicV1CompanyRoute
  '/api/public/v1/filings': typeof ApiPublicV1FilingsRouteWithChildren
  '/api/public/v1/fundamentals': typeof ApiPublicV1FundamentalsRoute
  '/api/public/v1/insider': typeof ApiPublicV1InsiderRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/filings/batch': typeof ApiPublicV1FilingsBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/companies/$ticker': typeof CompaniesTickerRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs/schema': typeof DocsSchemaRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/api/public/v1/clusters': typeof ApiPublicV1ClustersRoute
  '/api/public/v1/company': typeof ApiPublicV1CompanyRoute
  '/api/public/v1/filings': typeof ApiPublicV1FilingsRouteWithChildren
  '/api/public/v1/fundamentals': typeof ApiPublicV1FundamentalsRoute
  '/api/public/v1/insider': typeof ApiPublicV1InsiderRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/filings/batch': typeof ApiPublicV1FilingsBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/companies/$ticker': typeof CompaniesTickerRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs/schema': typeof DocsSchemaRoute
  '/examples/$slug': typeof ExamplesSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/api/public/v1/clusters': typeof ApiPublicV1ClustersRoute
  '/api/public/v1/company': typeof ApiPublicV1CompanyRoute
  '/api/public/v1/filings': typeof ApiPublicV1FilingsRouteWithChildren
  '/api/public/v1/fundamentals': typeof ApiPublicV1FundamentalsRoute
  '/api/public/v1/insider': typeof ApiPublicV1InsiderRoute
  '/api/public/v1/quote': typeof ApiPublicV1QuoteRoute
  '/api/public/v1/search': typeof ApiPublicV1SearchRoute
  '/api/public/v1/_internal/dispatch-webhooks': typeof ApiPublicV1InternalDispatchWebhooksRoute
  '/api/public/v1/filings/batch': typeof ApiPublicV1FilingsBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/examples'
    | '/login'
    | '/playground'
    | '/signup'
    | '/status'
    | '/companies/$ticker'
    | '/docs/sdk'
    | '/docs/schema'
    | '/examples/$slug'
    | '/vs/$competitor'
    | '/api/public/v1/clusters'
    | '/api/public/v1/company'
    | '/api/public/v1/filings'
    | '/api/public/v1/fundamentals'
    | '/api/public/v1/insider'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/api/public/v1/dispatch-webhooks'
    | '/api/public/v1/filings/batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/examples'
    | '/login'
    | '/playground'
    | '/signup'
    | '/status'
    | '/companies/$ticker'
    | '/docs/sdk'
    | '/docs/schema'
    | '/examples/$slug'
    | '/vs/$competitor'
    | '/api/public/v1/clusters'
    | '/api/public/v1/company'
    | '/api/public/v1/filings'
    | '/api/public/v1/fundamentals'
    | '/api/public/v1/insider'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/api/public/v1/dispatch-webhooks'
    | '/api/public/v1/filings/batch'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/dashboard'
    | '/docs'
    | '/examples'
    | '/login'
    | '/playground'
    | '/signup'
    | '/status'
    | '/companies/$ticker'
    | '/docs/sdk'
    | '/docs/schema'
    | '/examples/$slug'
    | '/vs/$competitor'
    | '/api/public/v1/clusters'
    | '/api/public/v1/company'
    | '/api/public/v1/filings'
    | '/api/public/v1/fundamentals'
    | '/api/public/v1/insider'
    | '/api/public/v1/quote'
    | '/api/public/v1/search'
    | '/api/public/v1/_internal/dispatch-webhooks'
    | '/api/public/v1/filings/batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  CompaniesTickerRoute: typeof CompaniesTickerRoute
  VsCompetitorRoute: typeof VsCompetitorRoute
  ApiPublicV1ClustersRoute: typeof ApiPublicV1ClustersRoute
  ApiPublicV1CompanyRoute: typeof ApiPublicV1CompanyRoute
  ApiPublicV1FilingsRoute: typeof ApiPublicV1FilingsRouteWithChildren
  ApiPublicV1FundamentalsRoute: typeof ApiPublicV1FundamentalsRoute
  ApiPublicV1InsiderRoute: typeof ApiPublicV1InsiderRoute
  ApiPublicV1QuoteRoute: typeof ApiPublicV1QuoteRoute
  ApiPublicV1SearchRoute: typeof ApiPublicV1SearchRoute
  ApiPublicV1InternalDispatchWebhooksRoute: typeof ApiPublicV1InternalDispatchWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$competitor': {
      id: '/vs/$competitor'
      path: '/vs/$competitor'
      fullPath: '/vs/$competitor'
      preLoaderRoute: typeof VsCompetitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$slug': {
      id: '/examples/$slug'
      path: '/$slug'
      fullPath: '/examples/$slug'
      preLoaderRoute: typeof ExamplesSlugRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/docs/sdk': {
      id: '/docs/sdk'
      path: '/sdk'
      fullPath: '/docs/sdk'
      preLoaderRoute: typeof DocsSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/schema': {
      id: '/docs/schema'
      path: '/schema'
      fullPath: '/docs/schema'
      preLoaderRoute: typeof DocsSchemaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/companies/$ticker': {
      id: '/companies/$ticker'
      path: '/companies/$ticker'
      fullPath: '/companies/$ticker'
      preLoaderRoute: typeof CompaniesTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/search': {
      id: '/api/public/v1/search'
      path: '/api/public/v1/search'
      fullPath: '/api/public/v1/search'
      preLoaderRoute: typeof ApiPublicV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/quote': {
      id: '/api/public/v1/quote'
      path: '/api/public/v1/quote'
      fullPath: '/api/public/v1/quote'
      preLoaderRoute: typeof ApiPublicV1QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/insider': {
      id: '/api/public/v1/insider'
      path: '/api/public/v1/insider'
      fullPath: '/api/public/v1/insider'
      preLoaderRoute: typeof ApiPublicV1InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fundamentals': {
      id: '/api/public/v1/fundamentals'
      path: '/api/public/v1/fundamentals'
      fullPath: '/api/public/v1/fundamentals'
      preLoaderRoute: typeof ApiPublicV1FundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/filings': {
      id: '/api/public/v1/filings'
      path: '/api/public/v1/filings'
      fullPath: '/api/public/v1/filings'
      preLoaderRoute: typeof ApiPublicV1FilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/company': {
      id: '/api/public/v1/company'
      path: '/api/public/v1/company'
      fullPath: '/api/public/v1/company'
      preLoaderRoute: typeof ApiPublicV1CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clusters': {
      id: '/api/public/v1/clusters'
      path: '/api/public/v1/clusters'
      fullPath: '/api/public/v1/clusters'
      preLoaderRoute: typeof ApiPublicV1ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/filings/batch': {
      id: '/api/public/v1/filings/batch'
      path: '/batch'
      fullPath: '/api/public/v1/filings/batch'
      preLoaderRoute: typeof ApiPublicV1FilingsBatchRouteImport
      parentRoute: typeof ApiPublicV1FilingsRoute
    }
    '/api/public/v1/_internal/dispatch-webhooks': {
      id: '/api/public/v1/_internal/dispatch-webhooks'
      path: '/api/public/v1/dispatch-webhooks'
      fullPath: '/api/public/v1/dispatch-webhooks'
      preLoaderRoute: typeof ApiPublicV1InternalDispatchWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSdkRoute: typeof DocsSdkRoute
  DocsSchemaRoute: typeof DocsSchemaRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSdkRoute: DocsSdkRoute,
  DocsSchemaRoute: DocsSchemaRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ExamplesRouteChildren {
  ExamplesSlugRoute: typeof ExamplesSlugRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesSlugRoute: ExamplesSlugRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

interface ApiPublicV1FilingsRouteChildren {
  ApiPublicV1FilingsBatchRoute: typeof ApiPublicV1FilingsBatchRoute
}

const ApiPublicV1FilingsRouteChildren: ApiPublicV1FilingsRouteChildren = {
  ApiPublicV1FilingsBatchRoute: ApiPublicV1FilingsBatchRoute,
}

const ApiPublicV1FilingsRouteWithChildren =
  ApiPublicV1FilingsRoute._addFileChildren(ApiPublicV1FilingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  CompaniesTickerRoute: CompaniesTickerRoute,
  VsCompetitorRoute: VsCompetitorRoute,
  ApiPublicV1ClustersRoute: ApiPublicV1ClustersRoute,
  ApiPublicV1CompanyRoute: ApiPublicV1CompanyRoute,
  ApiPublicV1FilingsRoute: ApiPublicV1FilingsRouteWithChildren,
  ApiPublicV1FundamentalsRoute: ApiPublicV1FundamentalsRoute,
  ApiPublicV1InsiderRoute: ApiPublicV1InsiderRoute,
  ApiPublicV1QuoteRoute: ApiPublicV1QuoteRoute,
  ApiPublicV1SearchRoute: ApiPublicV1SearchRoute,
  ApiPublicV1InternalDispatchWebhooksRoute:
    ApiPublicV1InternalDispatchWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
