// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctnzimlfmmyadfyfgtug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bnppbWxmbW15YWRmeWZndHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1Nzg1NDIsImV4cCI6MjA5MzE1NDU0Mn0.QBGURvMNrPA8Z_WNBq8TdDK0Tf5iwTVrW9-e5DOgLB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});