// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdosopezegatziozmhcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkb3NvcGV6ZWdhdHppb3ptaGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MTQ2MTIsImV4cCI6MjA5MzE5MDYxMn0.rSl5_oCqvzrkXd0jZ4EhziwuYh_0kPyScCY0Cxe1Zw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});